services:
  web3-proxy:
    image: alfredcapital/web3-proxy:2c359d8e8fa870254b35138fae94d329f0c9169e
    ports:
      - '8544:8544'
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -f http://web3-proxy:8544/health && exit 0 || exit 1',
        ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    volumes:
      - ./web3-proxy.toml:/web3-proxy.toml

  evm-block-fees:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    depends_on:
      web3-proxy:
        condition: service_healthy
    env_file:
      - .env
