[app]
chain_id = 1

# thundering herd protection
# only mark a block as the head block if the sum of their soft limits is greater than or equal to min_sum_soft_limit
min_sum_soft_limit = 1
# only mark a block as the head block if the number of servers with it is great than or equal to min_synced_rpcs
min_synced_rpcs = 1

# don't serve requests if the best known block is >60 seconds old
max_head_block_age = 60

# public limits are when no key is used. these are instead grouped by ip
# 0 = block all public requests
public_max_concurrent_requests = 1_000
# 0 = block all public requests
public_requests_per_period = 10_000

# 10GB of cache
response_cache_max_bytes = 10_000_000_000

# allowed_origin_requests_per_period changes the min_sum_soft_limit for requests with the specified (AND SPOOFABLE) Origin header
# origins not in the list for requests without an rpc_key will use public_requests_per_period instead
[app.allowed_origin_requests_per_period]
"https://chainlist.org" = 1_000

[balanced_rpcs]

    [balanced_rpcs.llamanodes]
    display_name = "LlamaNodes"
    block_data_limit = "archive"
    http_url = "https://ethereum.llamarpc.com"
    ws_url = "wss://ethereum.llamarpc.com"
    
    [balanced_rpcs.publicnode]
    display_name = "PublicNode"
    block_data_limit = "archive"
    http_url = "https://ethereum-rpc.publicnode.com"
    ws_url = "wss://ethereum-rpc.publicnode.com"    

    [balanced_rpcs.ankr]
    display_name = "Ankr"
    block_data_limit = 64
    http_url = "https://rpc.ankr.com/eth"
    soft_limit = 1_000

    [balanced_rpcs.cloudflare]
    display_name = "Cloudflare"
    http_url = "https://cloudflare-eth.com"
    soft_limit = 1_000

    [balanced_rpcs.mycryptoapi]
    display_name = "MyCrypto"
    disabled = true
    http_url = "https://api.mycryptoapi.com/eth"
    soft_limit = 1_000

    [balanced_rpcs.pokt-v1]
    display_name = "Pokt #1"
    http_url = "https://eth-mainnet.gateway.pokt.network/v1/5f3453978e354ab992c4da79"
    soft_limit = 500

    [balanced_rpcs.pokt]
    display_name = "Pokt #2"
    http_url = "https://eth-rpc.gateway.pokt.network"
    soft_limit = 500

    [balanced_rpcs.linkpool]
    display_name = "Linkpool"
    http_url = "https://main-rpc.linkpool.io"
    soft_limit = 500

    [balanced_rpcs.runonflux]
    display_name = "Run on Flux (light)"
    http_url = "https://ethereumnodelight.app.runonflux.io"
    soft_limit = 1_000

    # load balanced light nodes are not very reliable
    [balanced_rpcs.linkpool-light]
    display_name = "Linkpool (light)"
    disabled = true
    http_url = "https://main-light.eth.linkpool.io"
    soft_limit = 100

    [balanced_rpcs.publicnodes]
    display_name = "PublicNode"
    http_url = "https://ethereum-rpc.publicnode.com"
    ws_url = "wss://ethereum-rpc.publicnode.com"
    soft_limit = 1_000
    
    [balanced_rpcs.blastapi]
    display_name = "Blastapi"
    block_data_limit = 64
    http_url = "https://eth-mainnet.public.blastapi.io"
    ws_url= "wss://eth-mainnet.public.blastapi.io"
    soft_limit = 1_000

    [balanced_rpcs.drpc]
    display_name = "Drpc"
    http_url="https://eth.drpc.org"
    ws_url="wss://eth.drpc.org"
    soft_limit = 1_000
    
    [balanced_rpcs.tenderly]
    display_name = "Tenderly"
    ws_url="wss://mainnet.gateway.tenderly.co"
    soft_limit = 1_000

    [balanced_rpcs.noderpc]
    display_name = "MyCrypto"
    disabled = true
    http_url= "https://www.noderpc.xyz/rpc-mainnet/public"
    ws_url = "wss://www.noderpc.xyz/ws/rpc-mainnet/public"
    soft_limit = 1_000


[private_rpcs]

# these worked well on ETH 1.0, but 2.0 ends up not working as well. we will re-assess as more validators turn on private transactions

    [private_rpcs.eden]
    disabled = true
    display_name = "Eden network"
    http_url = "https://api.edennetwork.io/v1/"
    soft_limit = 1_805

    [private_rpcs.eden_beta]
    disabled = true
    display_name = "Eden network beta"
    http_url = "https://api.edennetwork.io/v1/beta"
    soft_limit = 5_861

    [private_rpcs.ethermine]
    disabled = true
    display_name = "Ethermine"
    http_url = "https://rpc.ethermine.org"
    soft_limit = 5_861

    [private_rpcs.flashbots]
    disabled = true
    display_name = "Flashbots Fast"
    http_url = "https://rpc.flashbots.net/fast"
    soft_limit = 7_074

    [private_rpcs.securerpc]
    disabled = true
    display_name = "SecureRPC"
    http_url = "https://gibson.securerpc.com/v1"
    soft_limit = 4_560
